# coding: utf-8

"""
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.

The version of the OpenAPI document: v2.3.0
Contact: joel@spacetraders.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.contracts_api import ContractsApi


class TestContractsApi(unittest.TestCase):
    """ContractsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContractsApi()

    def tearDown(self) -> None:
        pass

    def test_accept_contract(self) -> None:
        """Test case for accept_contract

        Accept Contract
        """
        pass

    def test_deliver_contract(self) -> None:
        """Test case for deliver_contract

        Deliver Cargo to Contract
        """
        pass

    def test_fulfill_contract(self) -> None:
        """Test case for fulfill_contract

        Fulfill Contract
        """
        pass

    def test_get_contract(self) -> None:
        """Test case for get_contract

        Get Contract
        """
        pass

    def test_get_contracts(self) -> None:
        """Test case for get_contracts

        List Contracts
        """
        pass

    def test_negotiate_contract(self) -> None:
        """Test case for negotiate_contract

        Negotiate Contract
        """
        pass


if __name__ == "__main__":
    unittest.main()
