# coding: utf-8

"""
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.

The version of the OpenAPI document: v2.3.0
Contact: joel@spacetraders.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_ship_ship_scan201_response_data import \
    CreateShipShipScan201ResponseData


class TestCreateShipShipScan201ResponseData(unittest.TestCase):
    """CreateShipShipScan201ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateShipShipScan201ResponseData:
        """Test CreateShipShipScan201ResponseData
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateShipShipScan201ResponseData`
        """
        model = CreateShipShipScan201ResponseData()
        if include_optional:
            return CreateShipShipScan201ResponseData(
                cooldown = openapi_client.models.cooldown.Cooldown(
                    ship_symbol = '0', 
                    total_seconds = 0, 
                    remaining_seconds = 0, 
                    expiration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                ships = [
                    openapi_client.models.scanned_ship.ScannedShip(
                        symbol = '', 
                        registration = openapi_client.models.ship_registration.ShipRegistration(
                            name = '0', 
                            faction_symbol = '0', 
                            role = 'FABRICATOR', ), 
                        nav = openapi_client.models.ship_nav.ShipNav(
                            system_symbol = '0', 
                            waypoint_symbol = '0', 
                            route = openapi_client.models.ship_nav_route.ShipNavRoute(
                                destination = openapi_client.models.ship_nav_route_waypoint.ShipNavRouteWaypoint(
                                    symbol = '0', 
                                    type = 'PLANET', 
                                    system_symbol = '0', 
                                    x = 56, 
                                    y = 56, ), 
                                origin = openapi_client.models.ship_nav_route_waypoint.ShipNavRouteWaypoint(
                                    symbol = '0', 
                                    type = 'PLANET', 
                                    system_symbol = '0', 
                                    x = 56, 
                                    y = 56, ), 
                                departure_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                arrival = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            status = 'IN_TRANSIT', 
                            flight_mode = 'CRUISE', ), 
                        frame = openapi_client.models.scanned_ship_frame.ScannedShip_frame(
                            symbol = '', ), 
                        reactor = openapi_client.models.scanned_ship_reactor.ScannedShip_reactor(
                            symbol = '', ), 
                        engine = openapi_client.models.scanned_ship_engine.ScannedShip_engine(
                            symbol = '', ), 
                        mounts = [
                            openapi_client.models.scanned_ship_mounts_inner.ScannedShip_mounts_inner(
                                symbol = '', )
                            ], )
                    ]
            )
        else:
            return CreateShipShipScan201ResponseData(
                cooldown = openapi_client.models.cooldown.Cooldown(
                    ship_symbol = '0', 
                    total_seconds = 0, 
                    remaining_seconds = 0, 
                    expiration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                ships = [
                    openapi_client.models.scanned_ship.ScannedShip(
                        symbol = '', 
                        registration = openapi_client.models.ship_registration.ShipRegistration(
                            name = '0', 
                            faction_symbol = '0', 
                            role = 'FABRICATOR', ), 
                        nav = openapi_client.models.ship_nav.ShipNav(
                            system_symbol = '0', 
                            waypoint_symbol = '0', 
                            route = openapi_client.models.ship_nav_route.ShipNavRoute(
                                destination = openapi_client.models.ship_nav_route_waypoint.ShipNavRouteWaypoint(
                                    symbol = '0', 
                                    type = 'PLANET', 
                                    system_symbol = '0', 
                                    x = 56, 
                                    y = 56, ), 
                                origin = openapi_client.models.ship_nav_route_waypoint.ShipNavRouteWaypoint(
                                    symbol = '0', 
                                    type = 'PLANET', 
                                    system_symbol = '0', 
                                    x = 56, 
                                    y = 56, ), 
                                departure_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                arrival = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            status = 'IN_TRANSIT', 
                            flight_mode = 'CRUISE', ), 
                        frame = openapi_client.models.scanned_ship_frame.ScannedShip_frame(
                            symbol = '', ), 
                        reactor = openapi_client.models.scanned_ship_reactor.ScannedShip_reactor(
                            symbol = '', ), 
                        engine = openapi_client.models.scanned_ship_engine.ScannedShip_engine(
                            symbol = '', ), 
                        mounts = [
                            openapi_client.models.scanned_ship_mounts_inner.ScannedShip_mounts_inner(
                                symbol = '', )
                            ], )
                    ],
        )
        """

    def testCreateShipShipScan201ResponseData(self):
        """Test CreateShipShipScan201ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
