# coding: utf-8

# flake8: noqa
"""
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.

The version of the OpenAPI document: v2.3.0
Contact: joel@spacetraders.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from openapi_client.models.accept_contract200_response import (
        AcceptContract200Response,
    )
    from openapi_client.models.accept_contract200_response_data import (
        AcceptContract200ResponseData,
    )
    from openapi_client.models.activity_level import ActivityLevel
    from openapi_client.models.agent import Agent
    from openapi_client.models.agent_event import AgentEvent
    from openapi_client.models.chart import Chart
    from openapi_client.models.chart_transaction import ChartTransaction
    from openapi_client.models.construction import Construction
    from openapi_client.models.construction_material import ConstructionMaterial
    from openapi_client.models.contract import Contract
    from openapi_client.models.contract_deliver_good import ContractDeliverGood
    from openapi_client.models.contract_payment import ContractPayment
    from openapi_client.models.contract_terms import ContractTerms
    from openapi_client.models.cooldown import Cooldown
    from openapi_client.models.create_chart201_response import CreateChart201Response
    from openapi_client.models.create_chart201_response_data import (
        CreateChart201ResponseData,
    )
    from openapi_client.models.create_ship_ship_scan201_response import (
        CreateShipShipScan201Response,
    )
    from openapi_client.models.create_ship_ship_scan201_response_data import (
        CreateShipShipScan201ResponseData,
    )
    from openapi_client.models.create_ship_system_scan201_response import (
        CreateShipSystemScan201Response,
    )
    from openapi_client.models.create_ship_system_scan201_response_data import (
        CreateShipSystemScan201ResponseData,
    )
    from openapi_client.models.create_ship_waypoint_scan201_response import (
        CreateShipWaypointScan201Response,
    )
    from openapi_client.models.create_ship_waypoint_scan201_response_data import (
        CreateShipWaypointScan201ResponseData,
    )
    from openapi_client.models.create_survey201_response import CreateSurvey201Response
    from openapi_client.models.create_survey201_response_data import (
        CreateSurvey201ResponseData,
    )
    from openapi_client.models.deliver_contract200_response import (
        DeliverContract200Response,
    )
    from openapi_client.models.deliver_contract200_response_data import (
        DeliverContract200ResponseData,
    )
    from openapi_client.models.deliver_contract_request import DeliverContractRequest
    from openapi_client.models.dock_ship200_response import DockShip200Response
    from openapi_client.models.dock_ship200_response_data import DockShip200ResponseData
    from openapi_client.models.extract_resources201_response import (
        ExtractResources201Response,
    )
    from openapi_client.models.extract_resources201_response_data import (
        ExtractResources201ResponseData,
    )
    from openapi_client.models.extraction import Extraction
    from openapi_client.models.extraction_yield import ExtractionYield
    from openapi_client.models.faction import Faction
    from openapi_client.models.faction_symbol import FactionSymbol
    from openapi_client.models.faction_trait import FactionTrait
    from openapi_client.models.faction_trait_symbol import FactionTraitSymbol
    from openapi_client.models.fulfill_contract200_response import (
        FulfillContract200Response,
    )
    from openapi_client.models.get_agent200_response import GetAgent200Response
    from openapi_client.models.get_agents200_response import GetAgents200Response
    from openapi_client.models.get_construction200_response import (
        GetConstruction200Response,
    )
    from openapi_client.models.get_contract200_response import GetContract200Response
    from openapi_client.models.get_contracts200_response import GetContracts200Response
    from openapi_client.models.get_error_codes200_response import (
        GetErrorCodes200Response,
    )
    from openapi_client.models.get_error_codes200_response_error_codes_inner import (
        GetErrorCodes200ResponseErrorCodesInner,
    )
    from openapi_client.models.get_faction200_response import GetFaction200Response
    from openapi_client.models.get_factions200_response import GetFactions200Response
    from openapi_client.models.get_jump_gate200_response import GetJumpGate200Response
    from openapi_client.models.get_market200_response import GetMarket200Response
    from openapi_client.models.get_mounts200_response import GetMounts200Response
    from openapi_client.models.get_my_account200_response import GetMyAccount200Response
    from openapi_client.models.get_my_account200_response_data import (
        GetMyAccount200ResponseData,
    )
    from openapi_client.models.get_my_account200_response_data_account import (
        GetMyAccount200ResponseDataAccount,
    )
    from openapi_client.models.get_my_agent200_response import GetMyAgent200Response
    from openapi_client.models.get_my_agent_events200_response import (
        GetMyAgentEvents200Response,
    )
    from openapi_client.models.get_my_factions200_response import (
        GetMyFactions200Response,
    )
    from openapi_client.models.get_my_factions200_response_data_inner import (
        GetMyFactions200ResponseDataInner,
    )
    from openapi_client.models.get_my_ship200_response import GetMyShip200Response
    from openapi_client.models.get_my_ship_cargo200_response import (
        GetMyShipCargo200Response,
    )
    from openapi_client.models.get_my_ships200_response import GetMyShips200Response
    from openapi_client.models.get_repair_ship200_response import (
        GetRepairShip200Response,
    )
    from openapi_client.models.get_repair_ship200_response_data import (
        GetRepairShip200ResponseData,
    )
    from openapi_client.models.get_scrap_ship200_response import GetScrapShip200Response
    from openapi_client.models.get_scrap_ship200_response_data import (
        GetScrapShip200ResponseData,
    )
    from openapi_client.models.get_ship_cooldown200_response import (
        GetShipCooldown200Response,
    )
    from openapi_client.models.get_ship_modules200_response import (
        GetShipModules200Response,
    )
    from openapi_client.models.get_ship_nav200_response import GetShipNav200Response
    from openapi_client.models.get_shipyard200_response import GetShipyard200Response
    from openapi_client.models.get_status200_response import GetStatus200Response
    from openapi_client.models.get_status200_response_announcements_inner import (
        GetStatus200ResponseAnnouncementsInner,
    )
    from openapi_client.models.get_status200_response_health import (
        GetStatus200ResponseHealth,
    )
    from openapi_client.models.get_status200_response_leaderboards import (
        GetStatus200ResponseLeaderboards,
    )
    from openapi_client.models.get_status200_response_leaderboards_most_credits_inner import (
        GetStatus200ResponseLeaderboardsMostCreditsInner,
    )
    from openapi_client.models.get_status200_response_leaderboards_most_submitted_charts_inner import (
        GetStatus200ResponseLeaderboardsMostSubmittedChartsInner,
    )
    from openapi_client.models.get_status200_response_links_inner import (
        GetStatus200ResponseLinksInner,
    )
    from openapi_client.models.get_status200_response_server_resets import (
        GetStatus200ResponseServerResets,
    )
    from openapi_client.models.get_status200_response_stats import (
        GetStatus200ResponseStats,
    )
    from openapi_client.models.get_supply_chain200_response import (
        GetSupplyChain200Response,
    )
    from openapi_client.models.get_supply_chain200_response_data import (
        GetSupplyChain200ResponseData,
    )
    from openapi_client.models.get_system200_response import GetSystem200Response
    from openapi_client.models.get_system_waypoints200_response import (
        GetSystemWaypoints200Response,
    )
    from openapi_client.models.get_system_waypoints_traits_parameter import (
        GetSystemWaypointsTraitsParameter,
    )
    from openapi_client.models.get_systems200_response import GetSystems200Response
    from openapi_client.models.get_waypoint200_response import GetWaypoint200Response
    from openapi_client.models.install_mount201_response import InstallMount201Response
    from openapi_client.models.install_mount201_response_data import (
        InstallMount201ResponseData,
    )
    from openapi_client.models.install_mount_request import InstallMountRequest
    from openapi_client.models.install_ship_module201_response import (
        InstallShipModule201Response,
    )
    from openapi_client.models.install_ship_module201_response_data import (
        InstallShipModule201ResponseData,
    )
    from openapi_client.models.install_ship_module_request import (
        InstallShipModuleRequest,
    )
    from openapi_client.models.jettison200_response import Jettison200Response
    from openapi_client.models.jettison200_response_data import Jettison200ResponseData
    from openapi_client.models.jettison_request import JettisonRequest
    from openapi_client.models.jump_gate import JumpGate
    from openapi_client.models.jump_ship200_response import JumpShip200Response
    from openapi_client.models.jump_ship200_response_data import JumpShip200ResponseData
    from openapi_client.models.jump_ship_request import JumpShipRequest
    from openapi_client.models.market import Market
    from openapi_client.models.market_trade_good import MarketTradeGood
    from openapi_client.models.market_transaction import MarketTransaction
    from openapi_client.models.meta import Meta
    from openapi_client.models.navigate_ship200_response import NavigateShip200Response
    from openapi_client.models.navigate_ship200_response_data import (
        NavigateShip200ResponseData,
    )
    from openapi_client.models.navigate_ship_request import NavigateShipRequest
    from openapi_client.models.negotiate_contract201_response import (
        NegotiateContract201Response,
    )
    from openapi_client.models.negotiate_contract201_response_data import (
        NegotiateContract201ResponseData,
    )
    from openapi_client.models.orbit_ship200_response import OrbitShip200Response
    from openapi_client.models.patch_ship_nav200_response import PatchShipNav200Response
    from openapi_client.models.patch_ship_nav_request import PatchShipNavRequest
    from openapi_client.models.public_agent import PublicAgent
    from openapi_client.models.purchase_cargo201_response import (
        PurchaseCargo201Response,
    )
    from openapi_client.models.purchase_cargo201_response_data import (
        PurchaseCargo201ResponseData,
    )
    from openapi_client.models.purchase_cargo_request import PurchaseCargoRequest
    from openapi_client.models.purchase_ship201_response import PurchaseShip201Response
    from openapi_client.models.purchase_ship201_response_data import (
        PurchaseShip201ResponseData,
    )
    from openapi_client.models.purchase_ship_request import PurchaseShipRequest
    from openapi_client.models.refuel_ship200_response import RefuelShip200Response
    from openapi_client.models.refuel_ship200_response_data import (
        RefuelShip200ResponseData,
    )
    from openapi_client.models.refuel_ship_request import RefuelShipRequest
    from openapi_client.models.register201_response import Register201Response
    from openapi_client.models.register201_response_data import Register201ResponseData
    from openapi_client.models.register_request import RegisterRequest
    from openapi_client.models.remove_mount201_response import RemoveMount201Response
    from openapi_client.models.remove_mount201_response_data import (
        RemoveMount201ResponseData,
    )
    from openapi_client.models.remove_mount_request import RemoveMountRequest
    from openapi_client.models.remove_ship_module201_response import (
        RemoveShipModule201Response,
    )
    from openapi_client.models.remove_ship_module_request import RemoveShipModuleRequest
    from openapi_client.models.repair_ship200_response import RepairShip200Response
    from openapi_client.models.repair_ship200_response_data import (
        RepairShip200ResponseData,
    )
    from openapi_client.models.repair_transaction import RepairTransaction
    from openapi_client.models.scanned_ship import ScannedShip
    from openapi_client.models.scanned_ship_engine import ScannedShipEngine
    from openapi_client.models.scanned_ship_frame import ScannedShipFrame
    from openapi_client.models.scanned_ship_mounts_inner import ScannedShipMountsInner
    from openapi_client.models.scanned_ship_reactor import ScannedShipReactor
    from openapi_client.models.scanned_system import ScannedSystem
    from openapi_client.models.scanned_waypoint import ScannedWaypoint
    from openapi_client.models.scrap_ship200_response import ScrapShip200Response
    from openapi_client.models.scrap_ship200_response_data import (
        ScrapShip200ResponseData,
    )
    from openapi_client.models.scrap_transaction import ScrapTransaction
    from openapi_client.models.sell_cargo201_response import SellCargo201Response
    from openapi_client.models.sell_cargo_request import SellCargoRequest
    from openapi_client.models.ship import Ship
    from openapi_client.models.ship_cargo import ShipCargo
    from openapi_client.models.ship_cargo_item import ShipCargoItem
    from openapi_client.models.ship_condition_event import ShipConditionEvent
    from openapi_client.models.ship_crew import ShipCrew
    from openapi_client.models.ship_engine import ShipEngine
    from openapi_client.models.ship_frame import ShipFrame
    from openapi_client.models.ship_fuel import ShipFuel
    from openapi_client.models.ship_fuel_consumed import ShipFuelConsumed
    from openapi_client.models.ship_modification_transaction import (
        ShipModificationTransaction,
    )
    from openapi_client.models.ship_module import ShipModule
    from openapi_client.models.ship_mount import ShipMount
    from openapi_client.models.ship_nav import ShipNav
    from openapi_client.models.ship_nav_flight_mode import ShipNavFlightMode
    from openapi_client.models.ship_nav_route import ShipNavRoute
    from openapi_client.models.ship_nav_route_waypoint import ShipNavRouteWaypoint
    from openapi_client.models.ship_nav_status import ShipNavStatus
    from openapi_client.models.ship_reactor import ShipReactor
    from openapi_client.models.ship_refine201_response import ShipRefine201Response
    from openapi_client.models.ship_refine201_response_data import (
        ShipRefine201ResponseData,
    )
    from openapi_client.models.ship_refine201_response_data_produced_inner import (
        ShipRefine201ResponseDataProducedInner,
    )
    from openapi_client.models.ship_refine_request import ShipRefineRequest
    from openapi_client.models.ship_registration import ShipRegistration
    from openapi_client.models.ship_requirements import ShipRequirements
    from openapi_client.models.ship_role import ShipRole
    from openapi_client.models.ship_type import ShipType
    from openapi_client.models.shipyard import Shipyard
    from openapi_client.models.shipyard_ship import ShipyardShip
    from openapi_client.models.shipyard_ship_crew import ShipyardShipCrew
    from openapi_client.models.shipyard_ship_types_inner import ShipyardShipTypesInner
    from openapi_client.models.shipyard_transaction import ShipyardTransaction
    from openapi_client.models.siphon import Siphon
    from openapi_client.models.siphon_resources201_response import (
        SiphonResources201Response,
    )
    from openapi_client.models.siphon_resources201_response_data import (
        SiphonResources201ResponseData,
    )
    from openapi_client.models.siphon_yield import SiphonYield
    from openapi_client.models.supply_construction201_response import (
        SupplyConstruction201Response,
    )
    from openapi_client.models.supply_construction201_response_data import (
        SupplyConstruction201ResponseData,
    )
    from openapi_client.models.supply_construction_request import (
        SupplyConstructionRequest,
    )
    from openapi_client.models.supply_level import SupplyLevel
    from openapi_client.models.survey import Survey
    from openapi_client.models.survey_deposit import SurveyDeposit
    from openapi_client.models.survey_size import SurveySize
    from openapi_client.models.system import System
    from openapi_client.models.system_faction import SystemFaction
    from openapi_client.models.system_type import SystemType
    from openapi_client.models.system_waypoint import SystemWaypoint
    from openapi_client.models.trade_good import TradeGood
    from openapi_client.models.trade_symbol import TradeSymbol
    from openapi_client.models.transfer_cargo200_response import (
        TransferCargo200Response,
    )
    from openapi_client.models.transfer_cargo200_response_data import (
        TransferCargo200ResponseData,
    )
    from openapi_client.models.transfer_cargo_request import TransferCargoRequest
    from openapi_client.models.waypoint import Waypoint
    from openapi_client.models.waypoint_faction import WaypointFaction
    from openapi_client.models.waypoint_modifier import WaypointModifier
    from openapi_client.models.waypoint_modifier_symbol import WaypointModifierSymbol
    from openapi_client.models.waypoint_orbital import WaypointOrbital
    from openapi_client.models.waypoint_trait import WaypointTrait
    from openapi_client.models.waypoint_trait_symbol import WaypointTraitSymbol
    from openapi_client.models.waypoint_type import WaypointType

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from openapi_client.models.accept_contract200_response import AcceptContract200Response
from openapi_client.models.accept_contract200_response_data import AcceptContract200ResponseData
from openapi_client.models.activity_level import ActivityLevel
from openapi_client.models.agent import Agent
from openapi_client.models.agent_event import AgentEvent
from openapi_client.models.chart import Chart
from openapi_client.models.chart_transaction import ChartTransaction
from openapi_client.models.construction import Construction
from openapi_client.models.construction_material import ConstructionMaterial
from openapi_client.models.contract import Contract
from openapi_client.models.contract_deliver_good import ContractDeliverGood
from openapi_client.models.contract_payment import ContractPayment
from openapi_client.models.contract_terms import ContractTerms
from openapi_client.models.cooldown import Cooldown
from openapi_client.models.create_chart201_response import CreateChart201Response
from openapi_client.models.create_chart201_response_data import CreateChart201ResponseData
from openapi_client.models.create_ship_ship_scan201_response import CreateShipShipScan201Response
from openapi_client.models.create_ship_ship_scan201_response_data import CreateShipShipScan201ResponseData
from openapi_client.models.create_ship_system_scan201_response import CreateShipSystemScan201Response
from openapi_client.models.create_ship_system_scan201_response_data import CreateShipSystemScan201ResponseData
from openapi_client.models.create_ship_waypoint_scan201_response import CreateShipWaypointScan201Response
from openapi_client.models.create_ship_waypoint_scan201_response_data import CreateShipWaypointScan201ResponseData
from openapi_client.models.create_survey201_response import CreateSurvey201Response
from openapi_client.models.create_survey201_response_data import CreateSurvey201ResponseData
from openapi_client.models.deliver_contract200_response import DeliverContract200Response
from openapi_client.models.deliver_contract200_response_data import DeliverContract200ResponseData
from openapi_client.models.deliver_contract_request import DeliverContractRequest
from openapi_client.models.dock_ship200_response import DockShip200Response
from openapi_client.models.dock_ship200_response_data import DockShip200ResponseData
from openapi_client.models.extract_resources201_response import ExtractResources201Response
from openapi_client.models.extract_resources201_response_data import ExtractResources201ResponseData
from openapi_client.models.extraction import Extraction
from openapi_client.models.extraction_yield import ExtractionYield
from openapi_client.models.faction import Faction
from openapi_client.models.faction_symbol import FactionSymbol
from openapi_client.models.faction_trait import FactionTrait
from openapi_client.models.faction_trait_symbol import FactionTraitSymbol
from openapi_client.models.fulfill_contract200_response import FulfillContract200Response
from openapi_client.models.get_agent200_response import GetAgent200Response
from openapi_client.models.get_agents200_response import GetAgents200Response
from openapi_client.models.get_construction200_response import GetConstruction200Response
from openapi_client.models.get_contract200_response import GetContract200Response
from openapi_client.models.get_contracts200_response import GetContracts200Response
from openapi_client.models.get_error_codes200_response import GetErrorCodes200Response
from openapi_client.models.get_error_codes200_response_error_codes_inner import GetErrorCodes200ResponseErrorCodesInner
from openapi_client.models.get_faction200_response import GetFaction200Response
from openapi_client.models.get_factions200_response import GetFactions200Response
from openapi_client.models.get_jump_gate200_response import GetJumpGate200Response
from openapi_client.models.get_market200_response import GetMarket200Response
from openapi_client.models.get_mounts200_response import GetMounts200Response
from openapi_client.models.get_my_account200_response import GetMyAccount200Response
from openapi_client.models.get_my_account200_response_data import GetMyAccount200ResponseData
from openapi_client.models.get_my_account200_response_data_account import GetMyAccount200ResponseDataAccount
from openapi_client.models.get_my_agent200_response import GetMyAgent200Response
from openapi_client.models.get_my_agent_events200_response import GetMyAgentEvents200Response
from openapi_client.models.get_my_factions200_response import GetMyFactions200Response
from openapi_client.models.get_my_factions200_response_data_inner import GetMyFactions200ResponseDataInner
from openapi_client.models.get_my_ship200_response import GetMyShip200Response
from openapi_client.models.get_my_ship_cargo200_response import GetMyShipCargo200Response
from openapi_client.models.get_my_ships200_response import GetMyShips200Response
from openapi_client.models.get_repair_ship200_response import GetRepairShip200Response
from openapi_client.models.get_repair_ship200_response_data import GetRepairShip200ResponseData
from openapi_client.models.get_scrap_ship200_response import GetScrapShip200Response
from openapi_client.models.get_scrap_ship200_response_data import GetScrapShip200ResponseData
from openapi_client.models.get_ship_cooldown200_response import GetShipCooldown200Response
from openapi_client.models.get_ship_modules200_response import GetShipModules200Response
from openapi_client.models.get_ship_nav200_response import GetShipNav200Response
from openapi_client.models.get_shipyard200_response import GetShipyard200Response
from openapi_client.models.get_status200_response import GetStatus200Response
from openapi_client.models.get_status200_response_announcements_inner import GetStatus200ResponseAnnouncementsInner
from openapi_client.models.get_status200_response_health import GetStatus200ResponseHealth
from openapi_client.models.get_status200_response_leaderboards import GetStatus200ResponseLeaderboards
from openapi_client.models.get_status200_response_leaderboards_most_credits_inner import GetStatus200ResponseLeaderboardsMostCreditsInner
from openapi_client.models.get_status200_response_leaderboards_most_submitted_charts_inner import GetStatus200ResponseLeaderboardsMostSubmittedChartsInner
from openapi_client.models.get_status200_response_links_inner import GetStatus200ResponseLinksInner
from openapi_client.models.get_status200_response_server_resets import GetStatus200ResponseServerResets
from openapi_client.models.get_status200_response_stats import GetStatus200ResponseStats
from openapi_client.models.get_supply_chain200_response import GetSupplyChain200Response
from openapi_client.models.get_supply_chain200_response_data import GetSupplyChain200ResponseData
from openapi_client.models.get_system200_response import GetSystem200Response
from openapi_client.models.get_system_waypoints200_response import GetSystemWaypoints200Response
from openapi_client.models.get_system_waypoints_traits_parameter import GetSystemWaypointsTraitsParameter
from openapi_client.models.get_systems200_response import GetSystems200Response
from openapi_client.models.get_waypoint200_response import GetWaypoint200Response
from openapi_client.models.install_mount201_response import InstallMount201Response
from openapi_client.models.install_mount201_response_data import InstallMount201ResponseData
from openapi_client.models.install_mount_request import InstallMountRequest
from openapi_client.models.install_ship_module201_response import InstallShipModule201Response
from openapi_client.models.install_ship_module201_response_data import InstallShipModule201ResponseData
from openapi_client.models.install_ship_module_request import InstallShipModuleRequest
from openapi_client.models.jettison200_response import Jettison200Response
from openapi_client.models.jettison200_response_data import Jettison200ResponseData
from openapi_client.models.jettison_request import JettisonRequest
from openapi_client.models.jump_gate import JumpGate
from openapi_client.models.jump_ship200_response import JumpShip200Response
from openapi_client.models.jump_ship200_response_data import JumpShip200ResponseData
from openapi_client.models.jump_ship_request import JumpShipRequest
from openapi_client.models.market import Market
from openapi_client.models.market_trade_good import MarketTradeGood
from openapi_client.models.market_transaction import MarketTransaction
from openapi_client.models.meta import Meta
from openapi_client.models.navigate_ship200_response import NavigateShip200Response
from openapi_client.models.navigate_ship200_response_data import NavigateShip200ResponseData
from openapi_client.models.navigate_ship_request import NavigateShipRequest
from openapi_client.models.negotiate_contract201_response import NegotiateContract201Response
from openapi_client.models.negotiate_contract201_response_data import NegotiateContract201ResponseData
from openapi_client.models.orbit_ship200_response import OrbitShip200Response
from openapi_client.models.patch_ship_nav200_response import PatchShipNav200Response
from openapi_client.models.patch_ship_nav_request import PatchShipNavRequest
from openapi_client.models.public_agent import PublicAgent
from openapi_client.models.purchase_cargo201_response import PurchaseCargo201Response
from openapi_client.models.purchase_cargo201_response_data import PurchaseCargo201ResponseData
from openapi_client.models.purchase_cargo_request import PurchaseCargoRequest
from openapi_client.models.purchase_ship201_response import PurchaseShip201Response
from openapi_client.models.purchase_ship201_response_data import PurchaseShip201ResponseData
from openapi_client.models.purchase_ship_request import PurchaseShipRequest
from openapi_client.models.refuel_ship200_response import RefuelShip200Response
from openapi_client.models.refuel_ship200_response_data import RefuelShip200ResponseData
from openapi_client.models.refuel_ship_request import RefuelShipRequest
from openapi_client.models.register201_response import Register201Response
from openapi_client.models.register201_response_data import Register201ResponseData
from openapi_client.models.register_request import RegisterRequest
from openapi_client.models.remove_mount201_response import RemoveMount201Response
from openapi_client.models.remove_mount201_response_data import RemoveMount201ResponseData
from openapi_client.models.remove_mount_request import RemoveMountRequest
from openapi_client.models.remove_ship_module201_response import RemoveShipModule201Response
from openapi_client.models.remove_ship_module_request import RemoveShipModuleRequest
from openapi_client.models.repair_ship200_response import RepairShip200Response
from openapi_client.models.repair_ship200_response_data import RepairShip200ResponseData
from openapi_client.models.repair_transaction import RepairTransaction
from openapi_client.models.scanned_ship import ScannedShip
from openapi_client.models.scanned_ship_engine import ScannedShipEngine
from openapi_client.models.scanned_ship_frame import ScannedShipFrame
from openapi_client.models.scanned_ship_mounts_inner import ScannedShipMountsInner
from openapi_client.models.scanned_ship_reactor import ScannedShipReactor
from openapi_client.models.scanned_system import ScannedSystem
from openapi_client.models.scanned_waypoint import ScannedWaypoint
from openapi_client.models.scrap_ship200_response import ScrapShip200Response
from openapi_client.models.scrap_ship200_response_data import ScrapShip200ResponseData
from openapi_client.models.scrap_transaction import ScrapTransaction
from openapi_client.models.sell_cargo201_response import SellCargo201Response
from openapi_client.models.sell_cargo_request import SellCargoRequest
from openapi_client.models.ship import Ship
from openapi_client.models.ship_cargo import ShipCargo
from openapi_client.models.ship_cargo_item import ShipCargoItem
from openapi_client.models.ship_condition_event import ShipConditionEvent
from openapi_client.models.ship_crew import ShipCrew
from openapi_client.models.ship_engine import ShipEngine
from openapi_client.models.ship_frame import ShipFrame
from openapi_client.models.ship_fuel import ShipFuel
from openapi_client.models.ship_fuel_consumed import ShipFuelConsumed
from openapi_client.models.ship_modification_transaction import ShipModificationTransaction
from openapi_client.models.ship_module import ShipModule
from openapi_client.models.ship_mount import ShipMount
from openapi_client.models.ship_nav import ShipNav
from openapi_client.models.ship_nav_flight_mode import ShipNavFlightMode
from openapi_client.models.ship_nav_route import ShipNavRoute
from openapi_client.models.ship_nav_route_waypoint import ShipNavRouteWaypoint
from openapi_client.models.ship_nav_status import ShipNavStatus
from openapi_client.models.ship_reactor import ShipReactor
from openapi_client.models.ship_refine201_response import ShipRefine201Response
from openapi_client.models.ship_refine201_response_data import ShipRefine201ResponseData
from openapi_client.models.ship_refine201_response_data_produced_inner import ShipRefine201ResponseDataProducedInner
from openapi_client.models.ship_refine_request import ShipRefineRequest
from openapi_client.models.ship_registration import ShipRegistration
from openapi_client.models.ship_requirements import ShipRequirements
from openapi_client.models.ship_role import ShipRole
from openapi_client.models.ship_type import ShipType
from openapi_client.models.shipyard import Shipyard
from openapi_client.models.shipyard_ship import ShipyardShip
from openapi_client.models.shipyard_ship_crew import ShipyardShipCrew
from openapi_client.models.shipyard_ship_types_inner import ShipyardShipTypesInner
from openapi_client.models.shipyard_transaction import ShipyardTransaction
from openapi_client.models.siphon import Siphon
from openapi_client.models.siphon_resources201_response import SiphonResources201Response
from openapi_client.models.siphon_resources201_response_data import SiphonResources201ResponseData
from openapi_client.models.siphon_yield import SiphonYield
from openapi_client.models.supply_construction201_response import SupplyConstruction201Response
from openapi_client.models.supply_construction201_response_data import SupplyConstruction201ResponseData
from openapi_client.models.supply_construction_request import SupplyConstructionRequest
from openapi_client.models.supply_level import SupplyLevel
from openapi_client.models.survey import Survey
from openapi_client.models.survey_deposit import SurveyDeposit
from openapi_client.models.survey_size import SurveySize
from openapi_client.models.system import System
from openapi_client.models.system_faction import SystemFaction
from openapi_client.models.system_type import SystemType
from openapi_client.models.system_waypoint import SystemWaypoint
from openapi_client.models.trade_good import TradeGood
from openapi_client.models.trade_symbol import TradeSymbol
from openapi_client.models.transfer_cargo200_response import TransferCargo200Response
from openapi_client.models.transfer_cargo200_response_data import TransferCargo200ResponseData
from openapi_client.models.transfer_cargo_request import TransferCargoRequest
from openapi_client.models.waypoint import Waypoint
from openapi_client.models.waypoint_faction import WaypointFaction
from openapi_client.models.waypoint_modifier import WaypointModifier
from openapi_client.models.waypoint_modifier_symbol import WaypointModifierSymbol
from openapi_client.models.waypoint_orbital import WaypointOrbital
from openapi_client.models.waypoint_trait import WaypointTrait
from openapi_client.models.waypoint_trait_symbol import WaypointTraitSymbol
from openapi_client.models.waypoint_type import WaypointType

""",
            name=__name__,
            doc=__doc__,
        )
    )
