# coding: utf-8

"""
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.

The version of the OpenAPI document: v2.3.0
Contact: joel@spacetraders.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict
from typing_extensions import Self

from openapi_client.models.agent import Agent
from openapi_client.models.cooldown import Cooldown
from openapi_client.models.market_transaction import MarketTransaction
from openapi_client.models.ship_nav import ShipNav


class JumpShip200ResponseData(BaseModel):
    """
    JumpShip200ResponseData
    """  # noqa: E501

    nav: ShipNav
    cooldown: Cooldown
    transaction: MarketTransaction
    agent: Agent
    __properties: ClassVar[List[str]] = ["nav", "cooldown", "transaction", "agent"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JumpShip200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of nav
        if self.nav:
            _dict["nav"] = self.nav.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cooldown
        if self.cooldown:
            _dict["cooldown"] = self.cooldown.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transaction
        if self.transaction:
            _dict["transaction"] = self.transaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of agent
        if self.agent:
            _dict["agent"] = self.agent.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JumpShip200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "nav": (
                    ShipNav.from_dict(obj["nav"])
                    if obj.get("nav") is not None
                    else None
                ),
                "cooldown": (
                    Cooldown.from_dict(obj["cooldown"])
                    if obj.get("cooldown") is not None
                    else None
                ),
                "transaction": (
                    MarketTransaction.from_dict(obj["transaction"])
                    if obj.get("transaction") is not None
                    else None
                ),
                "agent": (
                    Agent.from_dict(obj["agent"])
                    if obj.get("agent") is not None
                    else None
                ),
            }
        )
        return _obj
