# coding: utf-8

"""
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.

The version of the OpenAPI document: v2.3.0
Contact: joel@spacetraders.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated, Self

from openapi_client.models.ship_nav_flight_mode import ShipNavFlightMode
from openapi_client.models.ship_nav_route import ShipNavRoute
from openapi_client.models.ship_nav_status import ShipNavStatus


class ShipNav(BaseModel):
    """
    The navigation information of the ship.
    """  # noqa: E501

    system_symbol: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="The symbol of the system.", alias="systemSymbol"
    )
    waypoint_symbol: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="The symbol of the waypoint.", alias="waypointSymbol"
    )
    route: ShipNavRoute
    status: ShipNavStatus
    flight_mode: ShipNavFlightMode = Field(alias="flightMode")
    __properties: ClassVar[List[str]] = [
        "systemSymbol",
        "waypointSymbol",
        "route",
        "status",
        "flightMode",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ShipNav from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of route
        if self.route:
            _dict["route"] = self.route.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ShipNav from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "systemSymbol": obj.get("systemSymbol"),
                "waypointSymbol": obj.get("waypointSymbol"),
                "route": (
                    ShipNavRoute.from_dict(obj["route"])
                    if obj.get("route") is not None
                    else None
                ),
                "status": obj.get("status"),
                "flightMode": (
                    obj.get("flightMode")
                    if obj.get("flightMode") is not None
                    else ShipNavFlightMode.CRUISE
                ),
            }
        )
        return _obj
