name: CI Pipeline v2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.11]   # Test across multiple Python versions

    steps:
      # --- Checkout code ---
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- Setup Python ---
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # --- Install dependencies ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black isort

      # --- Linting (flake8) ---
      - name: Run flake8 (style checks)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      # --- Formatting (black) ---
      - name: Run black (formatting check)
        run: black --check .

      # --- Import sorting (isort) ---
      - name: Run isort (import sorting check)
        run: isort . --check-only

      # --- Run tests ---
      - name: Run tests
        run: PYTHONPATH=spacetraders-data-platform pytest --maxfail=3 --disable-warnings -q
