name: CI_V4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11]

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pre-commit

      # Run pre-commit hooks (black, isort, flake8)
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      # Set fake API token for tests
      - name: Set fake API token for tests
        run: echo "SPACETRADERS_TOKEN=fake-token" >> $GITHUB_ENV
      # Run tests
      - name: Run tests
        run: |
          PYTHONPATH=$PWD pytest --maxfail=3 --disable-warnings -q

