name: Docs and Architecture

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs_and_arch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install base deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install docs/analysis toolchain
        run: |
          pip install -r requirements-docs.txt
      - name: Build docs
        run: |
          mkdocs build --strict
      - name: Generate diagrams
        run: |
          python display/generate_diagrams.py
      - name: Lint import contracts
        run: |
          lint-imports
      - name: Upload diagram artifacts
        uses: actions/upload-artifact@v4
        with:
          name: diagrams
          path: display/diagrams

